export const mockGovernanceData = [
  {
    "id": "gov-demo-1",
    "programName": "Leadership Excellence Program 2026",
    "deliveryStatus": "Ongoing",
    "targetParticipants": 50,
    "reachedParticipants": 25,
    "evaluationEvidence": "Mid-program survey collected",
    "programTitle": "Leadership Excellence Program 2026",
    "assignedTcdexUnit": "LSE",
    "priorityLevel": "HIGH",
    "targetAudience": "Senior Managers",
    "businessUnitDevt": "Sales, Marketing",
    "programLead": "Jane Doe",
    "trainerType": "External",
    "internalTrainerNames": "",
    "externalVendor": "Acme Leadership Institute",
    "supportTeam": "John Smith",
    "naStatus": "COMPLETED",
    "identifiedNeedsSummary": "Gap in strategic decision making",
    "dataSources": "Performance Reviews 2025",
    "templateStatus": "DONE",
    "guidelines": "DONE",
    "sessionFlow": "DONE",
    "materials": "DONE",
    "deckStatus": "DONE",
    "budgetRequired": "YES",
    "approvedBudgetPhp": "500000.00",
    "headBudgetRequestStatus": "APPROVED",
    "paymentTracker": "50% Paid",
    "marketingPlanStatus": "DONE",
    "campaignAssets": "DONE",
    "commsSchedule": "DONE",
    "internalChannelsDeployment": "DONE",
    "scheduledDates": "Q1 - Q2 2026",
    "plannedDeliveryMonth": "March",
    "quarter": "Q1",
    "deliveryMode": "Hybrid",
    "attendanceConfirmation": "DONE",
    "facilitatorBriefing": "DONE",
    "dryRun": "DONE",
    "completion": "IN PROGRESS",
    "feedbackFormDeployment": "Deploy after session 3",
    "feedbackDeadline": "April 15, 2026",
    "feedbackReportStatus": "IN PROGRESS",
    "overallReportStatus": "PENDING",
    "recognitionSharing": "N/A",
    "followUp": "Scheduled for Q3",
    "reinforcementPlan": "Monthly check-ins"
  },
  {
    "id": "gov-demo-2",
    "programName": "New Hire Onboarding Bootcamp",
    "deliveryStatus": "Planned",
    "targetParticipants": 150,
    "reachedParticipants": 0,
    "evaluationEvidence": "Pending",
    "programTitle": "New Hire Onboarding Bootcamp",
    "assignedTcdexUnit": "TD",
    "priorityLevel": "MEDIUM",
    "targetAudience": "All new hires",
    "businessUnitDevt": "Company-wide",
    "programLead": "Alice Johnson",
    "trainerType": "Internal",
    "internalTrainerNames": "Bob Lee, Carol White",
    "externalVendor": "",
    "supportTeam": "HR Onboarding Team",
    "naStatus": "COMPLETED",
    "identifiedNeedsSummary": "Standardize onboarding experience",
    "dataSources": "Exit interviews, New hire surveys",
    "templateStatus": "IN PROGRESS",
    "guidelines": "DONE",
    "sessionFlow": "IN PROGRESS",
    "materials": "PENDING",
    "deckStatus": "PENDING",
    "budgetRequired": "NO",
    "approvedBudgetPhp": "0",
    "headBudgetRequestStatus": "N/A",
    "paymentTracker": "N/A",
    "marketingPlanStatus": "PENDING",
    "campaignAssets": "PENDING",
    "commsSchedule": "PENDING",
    "internalChannelsDeployment": "PENDING",
    "scheduledDates": "June 2026",
    "plannedDeliveryMonth": "June",
    "quarter": "Q2",
    "deliveryMode": "VILT",
    "attendanceConfirmation": "NOT STARTED",
    "facilitatorBriefing": "NOT STARTED",
    "dryRun": "NOT STARTED",
    "completion": "NOT STARTED",
    "feedbackFormDeployment": "Standard evaluation",
    "feedbackDeadline": "July 5, 2026",
    "feedbackReportStatus": "NOT STARTED",
    "overallReportStatus": "NOT STARTED",
    "recognitionSharing": "N/A",
    "followUp": "30-day survey",
    "reinforcementPlan": "Manager enablement guide"
  },
  {
    "id": "gov-demo-3",
    "programName": "DEIB Awareness Workshop",
    "deliveryStatus": "Completed",
    "targetParticipants": 200,
    "reachedParticipants": 195,
    "evaluationEvidence": "Full report submitted",
    "programTitle": "DEIB Awareness Workshop",
    "assignedTcdexUnit": "DEIB",
    "priorityLevel": "HIGH",
    "targetAudience": "All Employees",
    "businessUnitDevt": "Company-wide",
    "programLead": "David Kim",
    "trainerType": "External",
    "internalTrainerNames": "",
    "externalVendor": "Global Inclusion Partners",
    "supportTeam": "DEIB Council",
    "naStatus": "COMPLETED",
    "identifiedNeedsSummary": "Annual compliance and awareness",
    "dataSources": "Engagement Survey 2025",
    "templateStatus": "DONE",
    "guidelines": "DONE",
    "sessionFlow": "DONE",
    "materials": "DONE",
    "deckStatus": "DONE",
    "budgetRequired": "YES",
    "approvedBudgetPhp": "200000.00",
    "headBudgetRequestStatus": "APPROVED",
    "paymentTracker": "100% Paid",
    "marketingPlanStatus": "DONE",
    "campaignAssets": "DONE",
    "commsSchedule": "DONE",
    "internalChannelsDeployment": "DONE",
    "scheduledDates": "January 15, 2026",
    "plannedDeliveryMonth": "January",
    "quarter": "Q1",
    "deliveryMode": "VILT",
    "attendanceConfirmation": "DONE",
    "facilitatorBriefing": "DONE",
    "dryRun": "DONE",
    "completion": "COMPLETED",
    "feedbackFormDeployment": "Yes",
    "feedbackDeadline": "January 22, 2026",
    "feedbackReportStatus": "DONE",
    "overallReportStatus": "DONE",
    "recognitionSharing": "Shared in Townhall",
    "followUp": "Completed",
    "reinforcementPlan": "Quarterly DEIB newsletters"
  },
  {
    "id": "gov-demo-4",
    "programName": "Tech Skills: Advanced React",
    "deliveryStatus": "Delayed",
    "targetParticipants": 30,
    "reachedParticipants": 0,
    "evaluationEvidence": "N/A",
    "programTitle": "Tech Skills: Advanced React",
    "assignedTcdexUnit": "TD",
    "priorityLevel": "MEDIUM",
    "targetAudience": "Frontend Engineers",
    "businessUnitDevt": "Engineering",
    "programLead": "Eve Davis",
    "trainerType": "Internal",
    "internalTrainerNames": "Frank Wright",
    "externalVendor": "",
    "supportTeam": "Engineering Ops",
    "naStatus": "COMPLETED",
    "identifiedNeedsSummary": "Upskilling frontend team on Next.js",
    "dataSources": "Tech radar 2026",
    "templateStatus": "IN PROGRESS",
    "guidelines": "DONE",
    "sessionFlow": "IN PROGRESS",
    "materials": "IN PROGRESS",
    "deckStatus": "IN PROGRESS",
    "budgetRequired": "NO",
    "approvedBudgetPhp": "0",
    "headBudgetRequestStatus": "N/A",
    "paymentTracker": "N/A",
    "marketingPlanStatus": "PENDING",
    "campaignAssets": "PENDING",
    "commsSchedule": "PENDING",
    "internalChannelsDeployment": "PENDING",
    "scheduledDates": "TBD",
    "plannedDeliveryMonth": "Feb (Delayed)",
    "quarter": "Q1",
    "deliveryMode": "ILT",
    "attendanceConfirmation": "NOT STARTED",
    "facilitatorBriefing": "NOT STARTED",
    "dryRun": "NOT STARTED",
    "completion": "DELAYED",
    "feedbackFormDeployment": "TBD",
    "feedbackDeadline": "TBD",
    "feedbackReportStatus": "NOT STARTED",
    "overallReportStatus": "NOT STARTED",
    "recognitionSharing": "N/A",
    "followUp": "N/A",
    "reinforcementPlan": "N/A"
  }
];

export const mockGovernanceAuditLog = {
  id: "gov-demo-audit",
  date: new Date().toLocaleDateString(),
  fileName: "Demo_Static_Tracker_Data.xlsx",
  recordsProcessed: mockGovernanceData.length,
  statusSummary: {
    Completed: 1,
    Ongoing: 1,
    Planned: 1,
    Delayed: 1,
  },
  targetParticipants: 380,
  reachedParticipants: 220,
  evidenceSummary: {
    withEvidence: 2,
    total: 4
  },
  normalizedData: mockGovernanceData
};
